/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_usb_Hiddata */

#ifndef _Included_lib_usb_Hiddata
#define _Included_lib_usb_Hiddata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_usb_Hiddata
 * Method:    usbhidOpenDevice
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_lib_usb_Hiddata_usbhidOpenDevice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     lib_usb_Hiddata
 * Method:    usbhidCloseDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_lib_usb_Hiddata_usbhidCloseDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     lib_usb_Hiddata
 * Method:    usbhidSetReport
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_lib_usb_Hiddata_usbhidSetReport
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     lib_usb_Hiddata
 * Method:    usbhidGetReport
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_lib_usb_Hiddata_usbhidGetReport
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
